server:
  port: 8083
  tomcat:
    threads:
      max: 50 # 允许的最大线程数
    accept-count: 50 # 最大排队等待数量
    max-connections: 100 # 允许的最大连接
spring:
  rabbitmq:
    host: ${pm.mq.host:192.168.145.134}
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true # 开启feign对sentinel的支持
pm:
  swagger:
    title: 和平商城商家服务接口文档
    package: com.peacemall.shop.controller