server:
  port: 8087
  tomcat:
    threads:
      max: 50 # 允许的最大线程数
    accept-count: 50 # 最大排队等待数量
    max-connections: 100 # 允许的最大连接
spring:
  elasticsearch:
    uris: http://192.168.145.134:9200
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true # 开启feign对sentinel的支持
pm:
  swagger:
    title: 和平商城搜索服务接口文档
    package: com.peacemall.search.controller