server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**,/addresses/**

        - id: wallet
          uri: lb://wallet-service
          predicates:
            - Path=/wallet/**,/withdraw/**

        - id: shop
          uri: lb://shop-service
          predicates:
            - Path=/shops/**,/merchant-applications/**

        - id: product
          uri: lb://product-service
          predicates:
            - Path=/products/**,/product-images/**,/productsConfigurations/**,/categories/**

        - id: favorite
          uri: lb://favorite-service
          predicates:
            - Path=/favorites/**

pm:
  jwt:
    secret: "EBI0t1Rd1PchUR7RidJQo7QweK9ADXs0Kt/YG++d7II=" # 密钥
    expire: 86400 # 过期时间（秒） 1 天
  auth:
    excludePaths:
      - "/user/login"
      - "/user/register"
      - "/swagger-ui/**"