server:
  port: 8081
  tomcat:
    threads:
      max: 50 # 允许的最大线程数
    accept-count: 50 # 最大排队等待数量
    max-connections: 100 # 允许的最大连接
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true # 开启feign对sentinel的支持
pm:
  jwt:
    secret: "EBI0t1Rd1PchUR7RidJQo7QweK9ADXs0Kt/YG++d7II=" # 密钥
    expire: 86400000
  swagger:
    title: 和平商城钱包服务接口文档
    package: com.peacemall.wallet.controller